language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: WeLm8MFTMwEHXFTnU+pTmEa9Qf3l1COH47tW7l7pU3fpi9+y4kh+0PT14dzQfedE3SjxJwn+ol6k/slJw8Nluie8MclkYP1FtMVXg974iEPlsyhokE7Ks8BMERf4w2B4DxEMJGbrLz71onZNT4vpCT3poXrzX+WtREY/Y0xsoPOBfXB4Q1T31QnbQ3WYKs/O45qWXLiapyIKZI82BAC/uNfUuqQdIk4G2LxTUv0lgZBYlZRvWDJfd6+K82IAblmQJvACoAzOCHB+7nDlulZF+FYrqqbLmILvY0abffsRIPqtpti52AcZSIcGT1BWbBcZI12iP0dEtf7fCjXAkFca32T3LjNG5sXEUJKaEv6ZUEcdFQCE8J5Nf/mBDfJFXkje8bGPBov7Ga6CmzMh20+syJjPXyjOLAZDPbCLL/YF6SxsvZcq860x+8ipF4QZDUUvZ3v8WT/QLrE3YRpNZFaUONUVc3rDmT/u54TlqG+lvxTf/g3qbfzMvoPCV2fJ7fQqsPNdhfUB4DqC3mIC52DQ1W51ihk1AKCqJAjSQD7brkhWXxUFh7q5GAS0zHfmwYwTUEXLgAXz/QAi0EMGdDRNvXV3Q+EO2s7CoQ+QUpRWiDO+DYIB5LZAn8Cn4GQPPsvqgw88P4zCsxxm+WZag6J0mrp766T3JWJJPAqtg2nq+xY=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
