language: node_js
node_js:
  - "4"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "YebsueY1b2vOvZDb7fKCqJjDb0LTPPs9Z9RKtluyPwH1So/lwxw/jQMvqPFB+6ZJA9OPX4YeaJ7yrVsJsGwLpBTGysaLbuEBU2h+ldzz7ou9Vuq4IAw6lZHWaoHZLzj+E38mLODY3V5NKejFyF0Wwbg8KkNmn0t3POQbe2yi6Fl4Vj5FfXxmXLIy/tDzxBwz1SnShsgOnfu62N2LpHXgDaJks8KM3i3mP5tBd0nvZwhEPqJV7LgmJwFmbsnUR89pfPs+qj5SLvUTpocwYxQOuqFA11qZ03WyaRaG3KOruEVYYQ+dsLj3MUB3EPMd/yscqbkZCxHqW+xh/4S0gOT4Gve6v220XANv8+LEs3M3WoEZqKrrS6Iq25ZSjdkxiB9fsBLlrF+6gVEOyzgBODHxZs2vZ62Op8FqaomalPXt/PO3R44ECASbNhjRC6fd5SaeuwaR2uNy3y1FG1MfKJOoaex78WAUm/eJ6SqmcDoi3xkpTzI/h/Lazlikq0jcdwBi0abzA/HW/k0QKpr36G2E2ui7RW2NyCo1tSA57gO1b5x69fw2rNqONjeLayvorYv9peCe7augcGcWp2DW5kRVYuo4Oj+Ob22mRgSg95sFqdlEyt0NI84c43k/jpE2+9QpTj31XeolOI8dbQ/1hZyVx2WxqiNc1jRUhZyw6jGjPGM="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
