language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "Rw93pSmZIuGTgpd3LAAts5M1VuqnR+PFTzVj899zuaHxGdirQCph5PrwAHWVw7dgzaNlLW98oWBO/+1sFWefDFS4QYNecuwgEL4kPhLkaHw7njK5TvwMPQQC65lRzdFG5NUAv5N1SMBeCOsYn/1kbsO6eUy8IBtxQRylh2gXZLmLgcB9r2cRqqKc4517bS6kazLbC5v2V4p1kq97fhpWu7fjtW2yUInGtu94WKiBqzKjOL3MQQDgra5SqEL/eLNwnRCPi/y5Mc03vvdXhEDvTG7uS3yyA5knDNDhI3k0GbsOsMnR/hGGlbWHQbIcfwuyQhe+3uX7lgvnSyZ2T7HCXD2qNeqaCIV5fuPiBbKesvKC2wPzlBeOsTHIpW8EosSLmHJj2PKRw5xBcw/Vz4eB8P2fgpBwcBIbztd1YOyTxHkQHnzM7Y/beHfTDdmwhI8KrvCAWN2Z+WQwecUpaCWr5I1apzn4caAHyUiKKomnmeADd/hzmKc1KL8uVKZ3Ms7BOSh3YR8glRQddAGs4Xjo4Q2VuU36igECPKOr3wn2n9ABuIwIpqfQ1MeytjoaLlw5C6ejASZ6hWtvP/cMDuwjEl4UN2ExkFwSrMAiMRe/1u/M9qKa2e/zInox6E21Wdd8f8tz7LKyLuTpmohG5tjFaGok9fBCPLPn0BltM5cfIV0="
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
