language: node_js
node_js:
  - "4"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: GLsc4Gyc1TaaRgdsxssaIz508JlfzPKQxre1KznIsy6XUlm2FfmpaP5kxilq+U6cGSmd81ytU+cvq0gmgEi25N83voipOxYLjzTzgkt7Fi/usDk9/s+5j3/sqcZeKJSLuGAEarsejrwwc35dXN4jDXKqHbUb1rDbJwlkwwe2EeOVKuvstVKrfFzgK8r4go0PYZxBh3rX5lB30KCg/yETKB8h5+7BE9SspzSI2gRW9VzGGUHGZa7ywB6/ILkGWRcQv8vb+y2rS3rFcFtbNp7KL+e1XtnY6HwWuBjYEkoxnCNFSrPBRMaGDBqkEiszOsNQyftMhBpkFGsck4zDR3PnPfJgt504sYwx7wLusKAINASOBcXZUjdQCytbV75ceY4vYBRF28UBk0h+k8QBybXhUjT488uTMrCL6l2EZMtizYAK9MXn4+jbTKiJrP5EMNNaU/XeWf8HGXDG8xo83JXCRPOzsDHsdeyv6eBI5GvnmNSYiR54ADz1jBqsIwa3car3/pZUlpWYxlw1WIqHj715hnIFpUL3AoDgmQ4Cyz2cSixZVX8RiulXsqOV5v1/oUaxrvGWtAZ2+uRpg6/qnii33EnZylQyuVU0f68eE93YYsqiaRugr0Gw28mHaNvLHCkF/M9onLzW2uyXBMnhsW7mL37ZtvzObcs/+7/oEaazLcI=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
