language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=develop
  - secure: Vw3JkxpAjD3xd+dbzrGMzO4wD36/8LUEGi8sGDRpnha+Tyjs/Cl5tRJcSp+1eHsjFmbeXvHnBewJqivS25teyAU53UXJ3E22/LXgXGc5sUQoUhTe8TsRgAH9b3a5dAIVGn/o6Qp0wR7wziaIiPDzLmyL4z3J/jZJ/O7xAr65b8/PcPX1BHC4DhQ9fNc8ksHbjuMA+c3SOYyIpfmllXhoOlPhps7csAZGVYD9r+jOxkj68R9W9+KspEwK/uszCWJ+8RkWP2dBn8reXp76pqnXo5q4JiAXthfABPoa/yRz00EvRrseTSww0H6bceWsmo+g+YEE73FqF/1LIh7P+FtgQ0d58inPDyqyl/8FPxq66p9wJXQ1HRcikk3Symv9iPSRKfA4RHm0kv1hxpH7gizZ1smqVC8pRORpboGlAMxnPg82iM4qwbD+90zMb9WrQLS1rk+jxc9CJLKXZlmRcRiYBQOPauyF5X/u5nhsS2U4rE6SNtjrWB30Kg/4bCrEY6jbgLF3PgvrtNjPrQN7HDY/RP+M5+I6XBdDGHk8cx2b16FPIizEZRNLrpohwKYJmc3q4N2KL5PhSeIgY641XDj1yriZEbx+hUdau6wqd/pWACQVWH3O/3C4/xTmAi90UQXSjU19f3pONM60+08a07mJd9JbF94EsTTkTDZEE+D2r9Q=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- ./.build_scripts/lint.sh
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: "${DEPLOY_BRANCH}"
